### PR TITLE
Watchman

### PR DESCRIPTION
**Pull request by MalteKiefer**

### CODE REVIEW

**Comment by kwizart** [comment]
I've added you as a maintainer of the project given your past contributions.
Feel free to push changes.
Thx

PS: We might need to build or policy for things that can be introduced in fedy over things that need to be "advertised" via the usual "software" application (for gnome) or the related for others DE.

**Comment by MalteKiefer** [comment]
Maybe we should only Software that is not in the main repository.
When we have software included and this software becoming part of fedora, we should remove it with the next big release like from 5.x.x to 6.x.x here dino.

**Comment by MalteKiefer** [comment]
@kwizart I get no notification about by adding and I still have no rights here  😄 
Could you check the maintainer settings again?

**Comment by kwizart** [comment]
I will check later today...

**Pull request merged**
