### PR TITLE
Spotify fix

### PR DESCRIPTION
**Pull request by MalteKiefer**

### CODE REVIEW

**Comment by kwizart** [comment]
Hello, I disagree with this change, can you elaborate why you think it's needed ?

**Comment by MalteKiefer** [comment]
That is the reason:
```
[root@pinetree]/home/malte# 
dnf config-manager --set-disabled --repo=fedora-spotify
Fehler: Unbekannte Paketquelle: »fedora-spotify«
```
There is not repo for fedora-spotify in Fedora 31

**Comment by kwizart** [comment]
Indeed, so maybe it can be fixed by this instead:
dnf config-manager --set-disabled --repo=fedora-spotify -y  &>/dev/null || :

**Comment by kwizart** [comment]
I've fixed as appropriate.

**Pull request closed without merging**
