### PR TITLE
added alacritty

### PR DESCRIPTION
**Pull request by MalteKiefer**
Signed-off-by: Malte Kiefer <malte.kiefer@mailgermania.de>

@kwizart plz take a look.

### CODE REVIEW

**Comment by kwizart** [comment]
Looks good. Thx.

**Comment by leigh123linux** [comment]
I have a problem with the PR, can you pick another copr repo that uses python-3.7

https://copr-dist-git.fedorainfracloud.org/cgit/pschyska/alacritty/alacritty.git/tree/alacritty.spec?id=910f68b4a4c735037cf5b3e4e8cfff31d4971a30#n17

**Comment by leigh123linux** [comment]
Maybe try this copr instead

https://copr.fedorainfracloud.org/coprs/atim/alacritty/builds/

**Comment by kwizart** [comment]
Well, It's unfortunate that none already submitted alacritty for review in Fedora because once a fedora maintained version will be available, we might need to clean-up the copr repo activation in fedy.

**Comment by leigh123linux** [comment]
@kwizart  The packaging in atim's copr is better.

https://copr-dist-git.fedorainfracloud.org/cgit/atim/alacritty/alacritty.git/tree/alacritty.spec?id=4dfb3cff73b00951e4beaba945ea1666bccb6bfd

**Comment by MalteKiefer** [comment]
Strange, I used this repo to installed it, no errors.
Which version from Fedora did you use?

**Comment by leigh123linux** [comment]
@MalteKiefer  I use rawhide and F31.

**Comment by leigh123linux** [comment]
Sorry I didn't mean to close it :-)

**Comment by MalteKiefer** [comment]
Ok, changed in files. I add it now. I will release a new fedy version now.

**Comment by kwizart** [comment]
>Ok, changed in files. I add it now. I will release a new fedy version now.

You still forgot to bump the spec release. Please re-tag as end-users will not be able to update.

**Comment by MalteKiefer** [comment]
Already done.
Sorry

**Comment by kwizart** [comment]
5.0.6-1 is not legal in a version field, you need to use 5.0.6.1

**Comment by MalteKiefer** [comment]
I see the logs, :man_facepalming: 
I will fix it

**Pull request merged**
