### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by ilikelinux69**
The repository name changed to carlis/crow-translate

### CODE REVIEW

**Comment by MalteKiefer** [comment]
Same as before, because of this, closed

**Comment by ilikelinux69** [comment]
I made a request for the install.sh and uninstall.sh. If I make such a change (involves 2 Files) do I just need to send one pull request?

**Comment by MalteKiefer** [comment]
Sorry

**Comment by MalteKiefer** [comment]
Next time please in one PR

**Comment by kwizart** [comment]
@ilikelinux69 

Thanks for the PR
As Malte said, please only add one PR for a given feature.
You commit must also be meaningful to the plugin you update.

Also when we change from copr project, we need to disable the older one on remove to avoid broken copr repository to end users.

**Pull request merged**
