### PR TITLE
Feature/GitHub desktop

### PR DESCRIPTION
**Pull request by MalteKiefer**
@kwizart

### CODE REVIEW

**Comment by leigh123linux** [comment]
The repo is only el7 and has exceeded it's bandwidth.

**Comment by MalteKiefer** [comment]
It is not for el7 only, look at the GitHub page.
Here is a second mirror for that repo:

https://mirror.mwt.me/ghd/rpm

**Comment by leigh123linux** [comment]
> It is not for el7 only, look at the GitHub page. Here is a second mirror for that repo:
> 
> https://mirror.mwt.me/ghd/rpm

Please change the commit to use the mirror.

**Comment by MalteKiefer** [comment]
Done

**Comment by kwizart** [comment]
Merged, thanks.

Feel free to ping again if no answer from me.

**Pull request merged**
